from datetime import datetime


# =========================
# 1. 论文结构分析（Abstract / Contribution / Conclusion）
# =========================
def extract_sections_from_llm(client, context):
    prompt = f"""
你是一个严格的中文科研论文分析助手。

请完成以下任务：

1. Abstract（中文总结）
2. Contributions（中文要点列表）
3. Conclusion（中文总结）
4. SOTA vs Baseline 分析（中文）

⚠️ 要求：
- 必须全部中文输出
- 不允许编造实验数据
- 只基于给定论文内容
- 使用学术表达风格

论文内容：
{context}
"""

    response = client.chat.completions.create(
        model="deepseek-chat",
        messages=[
            {
                "role": "system",
                "content": "你是严格的中文科研论文审稿助手，只能输出中文内容"
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    return response.choices[0].message.content


# =========================
# 2. Markdown报告生成（最终版）
# =========================
def generate_markdown_report(answer, analysis_text, sota_analysis, table_summary):
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report = f"""
# 📄 Research Paper AI Report

Generated Time: {now}

---

## 🧠 1. Question Answering Result

{answer if answer else "No QA result generated"}

---

## 📊 2. Paper Analysis (Abstract / Contribution / Conclusion)

{analysis_text if analysis_text else "No analysis generated"}

---

## 🏆 3. SOTA vs Baseline Analysis

{sota_analysis if sota_analysis else "No SOTA analysis generated"}

---

## 📈 4. Extracted Experimental Tables

{table_summary if table_summary else "No tables extracted"}

---

## 🧾 5. Final Conclusion

This report is automatically generated by a Retrieval-Augmented Research Paper AI Agent.

It integrates:
- RAG-based question answering
- LLM-based paper understanding
- Experimental result extraction
- SOTA comparison analysis
"""

    return report